config/routes.rb
Rails.application.routes.draw do
  root 'letters#new'
  get '/letter/:id' , to: 'letters#show'
  post 'letters/create', to: 'letters#create'
  resources :letters
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :from_name,
            presence: true,
            length: {
                maximum: 6,
                too_long: "名前は６文字までしか入れられません"
            }
  validates :message,
            presence: true,
            length: { maximum: 200 }
  validates :to_name,
            presence: true,
            length: {
                maximum: 6,
                too_long: "名前は６文字までしか入れられません"
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/ogp_creator.rb
class OgpCreator
  require 'mini_magick'
  BASE_IMAGE_PATH = './app/assets/images/LetterTemplate.png'
  GRAVITY = 'center'
  TEXT_POSITION = '0,0'
  FROM_POSITION = '150,350'
  TO_POSITION = '-150,-300'
  FONT = './app/assets/fonts/HuiFont.ttf'
  FONT_SIZE = 32
  BODY_FONT_SIZE = 18
  INDENTION_COUNT = 16
  ROW_LIMIT = 16

  def self.build(text)
    text = prepare_text(text)
    @image = MiniMagick::Image.open(BASE_IMAGE_PATH)
    configuration1(text)
  end

  def self.from_build(text)
    text = prepare_text(text)
    from_configuration(text)
  end

  def self.to_build(text)
    text = prepare_text(text)
    to_configuration(text)
  end

  def self.write2(from, to)
    from_build(from)
    to_build(to)
    return @image
  end

  private
  def self.prepare_text(text)
    text.to_s.scan(/.{1,#{INDENTION_COUNT}}/)[0...ROW_LIMIT].join("\n")
  end

  def self.configuration1(text)
    @image.combine_options do |config|
      config.font FONT
      config.fill 'black'
      config.gravity GRAVITY
      config.pointsize FONT_SIZE
      config.draw "text #{TEXT_POSITION} '#{text}'"
    end
  end
  #from
  def self.from_configuration(text)
    @image.combine_options do |config|
      config.font FONT
      config.fill 'black'
      config.gravity GRAVITY
      config.pointsize FONT_SIZE
      config.draw "text #{FROM_POSITION} '#{text}'"
    end
  end

  #to
  def self.to_configuration(text)
    @image.combine_options do |config|
      config.font FONT
      config.fill 'black'
      config.gravity GRAVITY
      config.pointsize FONT_SIZE
      config.draw "text #{TO_POSITION} '#{text}'"
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def ogp
    text = ogp_params[:text]
    from = ogp_params[:from]
    to = ogp_params[:to]
    OgpCreator.build(text)
    image = OgpCreator.write2(from, to) #.tempfile.open.read
    @photo = Photo.new(image: image)
    @photo.save
    send_data image, :type => 'image/png',:disposition => 'inline'
  end

  def ogp_params
    params.permit(:text, :from, :to)
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show]

  # GET /letters/1
  # GET /letters/1.json
  def show
    # send_data @image.tempfile.open.read, :type => 'image/png',:disposition => 'inline'
  end

  # GET /letters/new
  def new
    @letter = Letter.new
  end

  # POST /letters
  # POST /letters.json
  def create
    @letter = Letter.new(letter_params)
    OgpCreator.build(@letter.message)
    @image = OgpCreator.write2(@letter.from_name + 'より', @letter.to_name + 'へ')
    @letter.image = @image
    respond_to do |format|
      if @letter.save
        format.html { redirect_to @letter, notice: '手紙を作成しました' }
        format.json { render :show, status: :created, location: @letter }
      else
        format.html { render :new }
        format.json { render json: @letter.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      @letter = Letter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:from_name, :message, :to_name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def og_image(path)
    if path
      provide(:image, path)
    else
      provide(:image, 'favicon.ico')
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def og_image(path)
    if path
      provide(:image, path)
    else
      provide(:image, 'favicon.ico')
    end
  end
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <%= link_to image_tag('favicon.ico'), root_path %>
  </div>
  <div>
    Letter for you
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Letter | <%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@ingtaTsuya_0801" />
    <meta property="og:title" content='君に手紙を書いたよ' />
    <meta content=<%= url_for(only_path: false) %> property="og:url">
    <meta property="og:image" content=<%= yield(:image) %> />
    <meta property="og:description" content='毎日の思いを伝えよう' />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/letters/_form.html.erb
<%= form_with(model: letter, local: true, id: 'new_letter') do |form| %>
  <% if letter.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% letter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
　<div class="letter">
      <div class="field to_box">
        <%= form.text_field :to_name, id: :letter_to_name, :placeholder => "宛名" %>
      </div>
      <div class="field msg_box">
        <%= form.text_area :message, id: :letter_message, :placeholder => "メッセージ" %>
      </div>
      <div class="field from_box">
        <%= form.text_field :from_name, id: :letter_from_name, :placeholder => "送り主" %>
      </div>
     <%= form.submit :投函する, class: 'btn actions' %>
  </div>
  <%= form.submit :投函する, class: 'phone_btn actions' %>

<% end %>

app/views/letters/edit.html.erb
<h1>Editing Letter</h1>

<%= render 'form', letter: @letter %>

<%= link_to 'Show', @letter %> |
<%= link_to 'Back', letters_path %>

app/views/letters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Letters</h1>
<div class="letters-container">
  <% @letters.each do |letter| %>
      <div class="coverTemplate">
        <%= letter.to_name  %>

      </div>
      <div><%= image_tag letter.image.url if letter.image? %></div>
      <div><%= link_to 'Show', letter %></div>
  <% end %>
</div>


<br>

<%= link_to 'New Letter', new_letter_path %>

app/views/letters/new.html.erb
<% provide(:title, "作成") %>

<%= render 'form', letter: @letter %>

app/views/letters/show.html.erb
<% og_image @letter.image.url if @letter.image? %>
<p id="notice"><%= notice %></p>


<div class="letters-container">
  <%= image_tag @letter.image.url if @letter.image? %>
</div>